-- ============================================================
-- Kastoori Medicals — Supplier Due Workflow Schema
-- Run this in the Supabase SQL Editor AFTER supabase-schema.sql.
-- Additive / idempotent (create if not exists), matches the conventions
-- of the existing schema (uuid pk, timestamptz, snake_case, RLS,
-- Realtime publication). Safe to run on an existing project.
--
-- Design notes (read before extending):
-- - No supplier master table exists yet in this project (supplier is
--   stored as free text elsewhere, e.g. supplier_bills.supplier_name),
--   so supplier_due.supplier_name is text, not a foreign key. If a
--   suppliers table is added later, migrate this column to supplier_id
--   then — don't add a parallel supplier_id column speculatively now.
-- - "Not Available" is a STATUS on supplier_due_items, not a separate
--   table. The existing not_available_items table is for a different
--   concept (can't dispense to a patient/dispensary order) and reusing
--   it here would conflate two different domains.
-- - Quantities are stored as `unit` + numeric, matching the pattern
--   already used in ocr_results (quantity numeric, pack_size text).
-- ============================================================

-- ---- supplier_due: one row per invoice that had a shortfall ----
create table if not exists public.supplier_due (
    id uuid primary key default gen_random_uuid(),
    supplier_name text not null,
    invoice_id uuid references public.supplier_bills(id) on delete set null,
    invoice_number text,
    status text not null default 'open' check (status in ('open', 'partially_supplied', 'closed', 'not_available')),
    created_by text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index if not exists idx_supplier_due_supplier on public.supplier_due (supplier_name);
create index if not exists idx_supplier_due_status on public.supplier_due (status);
create index if not exists idx_supplier_due_invoice on public.supplier_due (invoice_id);

-- ---- supplier_due_items: one row per medicine line short on that invoice ----
create table if not exists public.supplier_due_items (
    id uuid primary key default gen_random_uuid(),
    due_id uuid not null references public.supplier_due(id) on delete cascade,
    product_code text,                    -- Master Data Product Code, when matched
    medicine_id uuid,                     -- reserved for when Master Data gets a real uuid pk
    medicine_name text not null,
    strength text,
    ordered_quantity numeric not null,
    received_quantity numeric not null default 0,
    due_quantity numeric not null,        -- ordered_quantity - received_quantity, kept explicit (not computed) so history/audit rows can show what it was at the time, independent of later edits
    unit text default 'strips',
    reason text,                          -- e.g. "Partial supply", staff-entered
    status text not null default 'due' check (status in ('due', 'partially_supplied', 'supplied', 'not_available')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint due_quantity_non_negative check (due_quantity >= 0),
    constraint received_not_exceeding_ordered check (received_quantity <= ordered_quantity)
);
create index if not exists idx_supplier_due_items_due on public.supplier_due_items (due_id);
create index if not exists idx_supplier_due_items_code on public.supplier_due_items (product_code);
create index if not exists idx_supplier_due_items_status on public.supplier_due_items (status);

-- ---- supplier_due_history: append-only event log, one row per state change
--      (Partial Supply, Due Supplied, Due Closed, Not Available, etc.) ----
create table if not exists public.supplier_due_history (
    id uuid primary key default gen_random_uuid(),
    due_id uuid not null references public.supplier_due(id) on delete cascade,
    due_item_id uuid references public.supplier_due_items(id) on delete cascade,
    event_type text not null check (event_type in ('created', 'partial_supply', 'due_supplied', 'due_closed', 'not_available', 'reopened')),
    quantity numeric,
    previous_status text,
    new_status text,
    performed_by text,
    notes text,
    created_at timestamptz not null default now()
);
create index if not exists idx_supplier_due_history_due on public.supplier_due_history (due_id);
create index if not exists idx_supplier_due_history_item on public.supplier_due_history (due_item_id);
create index if not exists idx_supplier_due_history_time on public.supplier_due_history (created_at);

-- ---- supplier_due_notifications: one row per notification generated by
--      this workflow (New Due, Partial Supply, Due Supplied, Due Closed,
--      Not Available, Overdue Due) ----
create table if not exists public.supplier_due_notifications (
    id uuid primary key default gen_random_uuid(),
    due_id uuid references public.supplier_due(id) on delete cascade,
    due_item_id uuid references public.supplier_due_items(id) on delete cascade,
    notification_type text not null check (notification_type in ('new_due', 'partial_supply', 'due_supplied', 'due_closed', 'not_available', 'overdue_due')),
    title text not null,
    message text not null,
    is_read boolean not null default false,
    created_at timestamptz not null default now()
);
create index if not exists idx_supplier_due_notif_due on public.supplier_due_notifications (due_id);
create index if not exists idx_supplier_due_notif_unread on public.supplier_due_notifications (is_read);

-- ---- supplier_due_audit: immutable audit trail, one row per write
--      operation against this workflow (separate from history, which is
--      user-facing state-change events -- audit is the technical trail:
--      who, what table, what changed, when, from what device) ----
create table if not exists public.supplier_due_audit (
    id uuid primary key default gen_random_uuid(),
    due_id uuid references public.supplier_due(id) on delete set null,
    due_item_id uuid references public.supplier_due_items(id) on delete set null,
    action text not null,
    table_name text not null,
    before_value jsonb,
    after_value jsonb,
    performed_by text,
    device text,
    created_at timestamptz not null default now()
);
create index if not exists idx_supplier_due_audit_due on public.supplier_due_audit (due_id);
create index if not exists idx_supplier_due_audit_time on public.supplier_due_audit (created_at);

-- ============================================================
-- Atomic functions — same pattern as create_workflow_atomic() in the
-- main schema: each multi-table write happens inside one function so
-- two concurrent staff members can never leave the tables half-updated
-- relative to each other.
-- ============================================================

-- Creates a Supplier Due header + one item row + its history + notification
-- row in a single transaction, for one short-supplied medicine line on an
-- invoice. Called once per short line item during Bill Processing import.
create or replace function public.create_supplier_due_atomic(
    p_supplier_name text, p_invoice_id uuid, p_invoice_number text,
    p_product_code text, p_medicine_name text, p_strength text,
    p_ordered_quantity numeric, p_received_quantity numeric, p_unit text,
    p_reason text, p_created_by text
) returns uuid as $$
declare
    v_due_id uuid;
    v_item_id uuid;
    v_due_qty numeric := p_ordered_quantity - p_received_quantity;
    v_now timestamptz := now();
begin
    if v_due_qty <= 0 then
        raise exception 'create_supplier_due_atomic: due_quantity must be positive (ordered % received %)', p_ordered_quantity, p_received_quantity;
    end if;

    insert into public.supplier_due (supplier_name, invoice_id, invoice_number, status, created_by, created_at, updated_at)
    values (p_supplier_name, p_invoice_id, p_invoice_number, 'partially_supplied', p_created_by, v_now, v_now)
    returning id into v_due_id;

    insert into public.supplier_due_items (due_id, product_code, medicine_name, strength, ordered_quantity, received_quantity, due_quantity, unit, reason, status, created_at, updated_at)
    values (v_due_id, p_product_code, p_medicine_name, p_strength, p_ordered_quantity, p_received_quantity, v_due_qty, coalesce(p_unit, 'strips'), p_reason, 'due', v_now, v_now)
    returning id into v_item_id;

    insert into public.supplier_due_history (due_id, due_item_id, event_type, quantity, previous_status, new_status, performed_by, notes, created_at)
    values (v_due_id, v_item_id, 'created', v_due_qty, null, 'due', p_created_by, p_reason, v_now);

    insert into public.supplier_due_notifications (due_id, due_item_id, notification_type, title, message, created_at)
    values (v_due_id, v_item_id, 'partial_supply', 'Partial Supply — ' || p_medicine_name,
            p_medicine_name || coalesce(' ' || p_strength, '') || ': ordered ' || p_ordered_quantity || ', received ' || p_received_quantity || ', due ' || v_due_qty || ' ' || coalesce(p_unit, 'strips') || ' from ' || p_supplier_name || '.',
            v_now);

    insert into public.supplier_due_audit (due_id, due_item_id, action, table_name, after_value, performed_by, created_at)
    values (v_due_id, v_item_id, 'create_supplier_due', 'supplier_due_items',
            jsonb_build_object('ordered_quantity', p_ordered_quantity, 'received_quantity', p_received_quantity, 'due_quantity', v_due_qty),
            p_created_by, v_now);

    return v_item_id;
end;
$$ language plpgsql security definer;

-- Reconciles a Due Supplied entry against an existing due item: reduces
-- due_quantity, updates status (partially_supplied while due_quantity > 0,
-- supplied once it reaches 0), writes history + notification + audit, all
-- atomically so a due item can never be observed in a state where the
-- quantity was reduced but the history/notification wasn't written.
create or replace function public.reconcile_due_supplied_atomic(
    p_due_item_id uuid, p_supplied_quantity numeric, p_performed_by text
) returns void as $$
declare
    v_due_id uuid;
    v_current_due numeric;
    v_new_due numeric;
    v_new_status text;
    v_medicine_name text;
    v_unit text;
    v_now timestamptz := now();
begin
    select due_id, due_quantity, medicine_name, unit
      into v_due_id, v_current_due, v_medicine_name, v_unit
      from public.supplier_due_items where id = p_due_item_id
      for update;                          -- row lock: two staff can't reconcile the same item concurrently past its actual due amount

    if v_due_id is null then
        raise exception 'reconcile_due_supplied_atomic: due item % not found', p_due_item_id;
    end if;
    if p_supplied_quantity <= 0 then
        raise exception 'reconcile_due_supplied_atomic: supplied_quantity must be positive';
    end if;
    if p_supplied_quantity > v_current_due then
        raise exception 'reconcile_due_supplied_atomic: supplied quantity % exceeds outstanding due %', p_supplied_quantity, v_current_due;
    end if;

    v_new_due := v_current_due - p_supplied_quantity;
    v_new_status := case when v_new_due <= 0 then 'supplied' else 'partially_supplied' end;

    update public.supplier_due_items
       set due_quantity = v_new_due, received_quantity = received_quantity + p_supplied_quantity,
           status = v_new_status, updated_at = v_now
     where id = p_due_item_id;

    insert into public.supplier_due_history (due_id, due_item_id, event_type, quantity, previous_status, new_status, performed_by, created_at)
    values (v_due_id, p_due_item_id, 'due_supplied', p_supplied_quantity, 'due', v_new_status, p_performed_by, v_now);

    insert into public.supplier_due_notifications (due_id, due_item_id, notification_type, title, message, created_at)
    values (v_due_id, p_due_item_id,
            case when v_new_due <= 0 then 'due_closed' else 'due_supplied' end,
            case when v_new_due <= 0 then 'Due Closed — ' || v_medicine_name else 'Due Supplied — ' || v_medicine_name end,
            v_medicine_name || ': ' || p_supplied_quantity || ' ' || coalesce(v_unit, 'strips') || ' received. ' ||
                case when v_new_due <= 0 then 'Due fully closed.' else 'Remaining due: ' || v_new_due || ' ' || coalesce(v_unit, 'strips') || '.' end,
            v_now);

    insert into public.supplier_due_audit (due_id, due_item_id, action, table_name, before_value, after_value, performed_by, created_at)
    values (v_due_id, p_due_item_id, 'reconcile_due_supplied', 'supplier_due_items',
            jsonb_build_object('due_quantity', v_current_due),
            jsonb_build_object('due_quantity', v_new_due, 'status', v_new_status),
            p_performed_by, v_now);

    -- If every item under this due header is resolved, close the header too.
    if not exists (select 1 from public.supplier_due_items where due_id = v_due_id and status in ('due', 'partially_supplied')) then
        update public.supplier_due set status = 'closed', updated_at = v_now where id = v_due_id;
    end if;
end;
$$ language plpgsql security definer;

-- Marks a due item Not Available: it stops counting as outstanding supplier
-- debt. Kept as its own function (rather than inline UPDATE from the client)
-- so the history/notification/audit rows can never be skipped.
create or replace function public.mark_due_not_available_atomic(
    p_due_item_id uuid, p_reason text, p_performed_by text
) returns void as $$
declare
    v_due_id uuid;
    v_medicine_name text;
    v_now timestamptz := now();
begin
    select due_id, medicine_name into v_due_id, v_medicine_name
      from public.supplier_due_items where id = p_due_item_id for update;

    if v_due_id is null then
        raise exception 'mark_due_not_available_atomic: due item % not found', p_due_item_id;
    end if;

    update public.supplier_due_items
       set status = 'not_available', updated_at = v_now
     where id = p_due_item_id;

    insert into public.supplier_due_history (due_id, due_item_id, event_type, previous_status, new_status, performed_by, notes, created_at)
    values (v_due_id, p_due_item_id, 'not_available', 'due', 'not_available', p_performed_by, p_reason, v_now);

    insert into public.supplier_due_notifications (due_id, due_item_id, notification_type, title, message, created_at)
    values (v_due_id, p_due_item_id, 'not_available', 'Not Available — ' || v_medicine_name,
            v_medicine_name || ' marked Not Available by supplier.' || coalesce(' Reason: ' || p_reason, ''), v_now);

    insert into public.supplier_due_audit (due_id, due_item_id, action, table_name, after_value, performed_by, created_at)
    values (v_due_id, p_due_item_id, 'mark_not_available', 'supplier_due_items', jsonb_build_object('status', 'not_available', 'reason', p_reason), p_performed_by, v_now);

    if not exists (select 1 from public.supplier_due_items where due_id = v_due_id and status in ('due', 'partially_supplied')) then
        update public.supplier_due set status = 'closed', updated_at = v_now where id = v_due_id;
    end if;
end;
$$ language plpgsql security definer;

-- ---- Reporting views (Priority 11: Outstanding Due, Due by Supplier,
--      Due by Medicine, Due Aging) ----
create or replace view public.v_outstanding_supplier_due as
select sdi.id as due_item_id, sd.id as due_id, sd.supplier_name, sd.invoice_number,
       sdi.product_code, sdi.medicine_name, sdi.strength, sdi.due_quantity, sdi.unit,
       sdi.status, sd.created_at,
       (current_date - sd.created_at::date) as age_days
  from public.supplier_due_items sdi
  join public.supplier_due sd on sd.id = sdi.due_id
 where sdi.status in ('due', 'partially_supplied');

create or replace view public.v_due_by_supplier as
select supplier_name, count(*) as open_items, sum(due_quantity) as total_due_quantity
  from public.v_outstanding_supplier_due
 group by supplier_name;

create or replace view public.v_due_by_medicine as
select medicine_name, strength, product_code, count(*) as open_items, sum(due_quantity) as total_due_quantity
  from public.v_outstanding_supplier_due
 group by medicine_name, strength, product_code;

create or replace view public.v_due_aging as
select due_item_id, supplier_name, medicine_name, due_quantity, age_days,
       case when age_days <= 3 then '0-3 days' when age_days <= 7 then '4-7 days' when age_days <= 14 then '8-14 days' else '15+ days' end as age_bucket
  from public.v_outstanding_supplier_due;

-- ============================================================
-- RLS + Realtime (same policy shape as the rest of the schema)
-- ============================================================
alter table public.supplier_due enable row level security;
drop policy if exists "authenticated read" on public.supplier_due;
create policy "authenticated read" on public.supplier_due for select using (auth.role() = 'authenticated');
drop policy if exists "authenticated write" on public.supplier_due;
create policy "authenticated write" on public.supplier_due for all using (auth.role() = 'authenticated');

alter table public.supplier_due_items enable row level security;
drop policy if exists "authenticated read" on public.supplier_due_items;
create policy "authenticated read" on public.supplier_due_items for select using (auth.role() = 'authenticated');
drop policy if exists "authenticated write" on public.supplier_due_items;
create policy "authenticated write" on public.supplier_due_items for all using (auth.role() = 'authenticated');

alter table public.supplier_due_history enable row level security;
drop policy if exists "authenticated read" on public.supplier_due_history;
create policy "authenticated read" on public.supplier_due_history for select using (auth.role() = 'authenticated');
drop policy if exists "authenticated write" on public.supplier_due_history;
create policy "authenticated write" on public.supplier_due_history for insert with check (auth.role() = 'authenticated');

alter table public.supplier_due_notifications enable row level security;
drop policy if exists "authenticated read" on public.supplier_due_notifications;
create policy "authenticated read" on public.supplier_due_notifications for select using (auth.role() = 'authenticated');
drop policy if exists "authenticated write" on public.supplier_due_notifications;
create policy "authenticated write" on public.supplier_due_notifications for all using (auth.role() = 'authenticated');

alter table public.supplier_due_audit enable row level security;
drop policy if exists "authenticated read" on public.supplier_due_audit;
create policy "authenticated read" on public.supplier_due_audit for select using (auth.role() = 'authenticated');
drop policy if exists "authenticated write" on public.supplier_due_audit;
create policy "authenticated write" on public.supplier_due_audit for insert with check (auth.role() = 'authenticated');

do $$
begin
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'supplier_due') then
        alter publication supabase_realtime add table public.supplier_due;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'supplier_due_items') then
        alter publication supabase_realtime add table public.supplier_due_items;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'supplier_due_notifications') then
        alter publication supabase_realtime add table public.supplier_due_notifications;
    end if;
end $$;
